@startuml
' skinparam handwritten true
 left to right direction
 actor nirshman #IndianRed
 actor campaigner #AliceBlue
 actor viewer

rectangle hearUs {
    usecase MKS as "maintain\nKnesset\nstate"
    usecase CreateC as "create campaign"
    usecase manageCampaign as "manage campaign\ngo live"
    usecase updateCampaign as "update KM\nstatus per campaign"
    usecase login
    usecase choose as "Choose Campaigns"
    usecase viewC as "view campaign"
    usercase inviteUser as "Invite User"
    usercase inviteEmail as "Invite\nby email"

    nirshman -- MKS
    nirshman -- CreateC 
    nirshman -- login

    manageCampaign -- campaigner
    updateCampaign -- campaigner
    inviteUser     -- campaigner
    inviteEmail    -- campaigner
    choose -- campaigner
    login -- campaigner
    
    choose .> login : includes
    CreateC .> login 
    manageCampagin .> login 
    MKS .> login 

    viewer -- viewC
}

@enduml